### ISSUE TITLE
arning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by efriandika** [react-component/input-number#302]
I find this error when upgrating to v7

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at InputNumber (/Users/efriandika/P/JS/ic-next/node_modules/rc-input-number/lib/InputNumber.js:59:32)
    at div
    at Col (/Users/efriandika/P/JS/ic-next/node_modules/react-bootstrap/cjs/Col.js:22:23)
    at div
    at Row (/Users/efriandika/P/JS/ic-next/node_modules/react-bootstrap/cjs/Row.js:24:23)
    at div
```

Eventually I rollback the version to v6

**Comment by HellCatVN** [comment]
I have the same problem
